auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: geekitproblog.com
url: http://geekitproblog.com
feed: /atom.xml
author_info: <a href="http://someone.com/">Tommy</a>
